---
- name: Desplegar Infection Monkey AppImage
  hosts: localhost
  become: yes
  tasks:

    - name: Asegurar que libfuse2 está instalada
      apt:
        name: libfuse2
        state: present
        update_cache: yes

    - name: Descargar Infection Monkey v2.0.0 AppImage
      get_url:
        url: "https://sourceforge.net/projects/infection-monkey.mirror/files/v2.0.0/InfectionMonkey-v2.0.0.AppImage/download"
        dest: "/opt/InfectionMonkey-v2.0.0.AppImage"
        mode: '0755'

    - name: Crear servicio systemd para Infection Monkey
      copy:
        dest: /etc/systemd/system/infection-monkey.service
        content: |
          [Unit]
          Description=Infection Monkey Server
          After=network.target

          [Service]
          ExecStart=/opt/InfectionMonkey-v2.0.0.AppImage
          WorkingDirectory=/opt
          Restart=always
          User=root

          [Install]
          WantedBy=multi-user.target

    - name: Recargar systemd
      command: systemctl daemon-reexec

    - name: Habilitar e iniciar el servicio
      systemd:
        name: infection-monkey
        enabled: yes
        state: started

